name: Somking test suit

on:
  workflow_dispatch:
    inputs:
       axon_linux_release_tag:
        description: 'Linux release tag to download && run somking test'
        required: true

jobs:
   Smoking-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Download&Unzip
      run: |
        tag="${{ github.event.inputs.axon_linux_release_tag }}"
        package_name="axon_"$tag"_x86_64-unknown-linux-gnu.tar.gz"
        curl -L https://github.com/${{ GITHUB.REPOSITORY }}/releases/download/$tag/$package_name -o $package_name
        tar -zxf $package_name
        rm -rf $package_name
        mv axon_* axon
    - name: Start axon
      run: |
         cd ${{ github.workspace }}/axon
         ./axon init --config ${{ github.workspace }}/axon/config.toml --chain-spec ${{ github.workspace }}/axon/specs/single_node/chain-spec.toml > /tmp/log 2>&1
         ./axon run  --config ${{ github.workspace }}/axon/config.toml >> /tmp/log 2>&1 &
         sleep 120
    - name: Check Axon Status
      run: |
         first_block_json=$(echo '{
            "id": 1,
            "jsonrpc": "2.0",
            "method": "eth_blockNumber",
            "params": [
            ]
          }' \
          | tr -d '\n' \
          | curl -H 'content-type: application/json' -d @- \
          http://127.0.0.1:8000)
         FIST_BLOCK_NUMBER=$(echo $first_block_json | jq --raw-output '.result')
         FIST_BLOCK_NUMBER=$(printf %d $TIP_BLOCK_NUMBER)
         echo $FIST_BLOCK_NUMBER
         sleep 300
         second_block_json=$(echo '{
            "id": 1,
            "jsonrpc": "2.0",
            "method": "eth_blockNumber",
            "params": [
            ]
          }' \
          | tr -d '\n' \
          | curl -H 'content-type: application/json' -d @- \
          http://127.0.0.1:8000)
         SECOND_TIP_BLOCK_NUMBER=$(echo $second_block_json | jq --raw-output '.result')
         SECOND_TIP_BLOCK_NUMBER=$(printf %d $SECOND_TIP_BLOCK_NUMBER)
         echo $SECOND_TIP_BLOCK_NUMBER
         if [ $FIST_BLOCK_NUMBER == $SECOND_TIP_BLOCK_NUMBER ]; then
            echo "Tip block number No update in 5mins"
            exit 1
         fi
    - name: Send some mail
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.163.com
        server_port: 465
        secure: true
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Smoking test failed on release ${{ github.event.inputs.axon_linux_release_tag }}
        body: Smoking test failed on release ${{ github.event.inputs.axon_linux_release_tag }},please have a check!
        to: ${{secrets.MAIL_ADDRS}}
        from: github_action
